### PR TITLE
Add a table for F# wrappers for popular .NET libraries

### PR DESCRIPTION
**Pull request by Happypig375**

### CODE REVIEW

**Comment by Neftedollar** [comment]
@Happypig375 this list already contains Giraffe and few other. 
Section Wrappers around dotnet libs is not correct, couse F# is already .net, please use existing categories

**Comment by Happypig375** [comment]
@Neftedollar They are mixed within a lot of other smaller libraries, making the "standard wrappers" harder to find.

**Comment by Neftedollar** [comment]
@Happypig375 You can add this smaller libraries without duplication and without category "wrapper". If you will do it, please send another PR or change this PR.

**Comment by Happypig375** [comment]
@Neftedollar What I mean is that
- Person would like to look for the F# wrapper of some C# library.
- This list is too long for effective searching.

**Comment by WhiteBlackGoose** [comment]
@Neftedollar so what are the current thoughts? I think it's a useful list. Libraries made in C# are normally much more popular for software/desktop etc. development, so people might want to search by them, and seeing what F# equivalents those have.

**Comment by Neftedollar** [comment]
merged, thanx

**Pull request merged**
